name: Bug Report 🐛
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        * make sure you are able to repro it on the latest released version.
        You can install the latest version from the [PowerShell Gallery ](https://www.powershellgallery.com/packages/VSTeam)
        * Search the existing issues.
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Give us the steps (bullet points are enough for text) and the script that you used.
      placeholder: Tell us your steps and your script
      value: |
        ```powershell

        ```
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What was your expected outcome?
      value: I expected that...
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior?
      description: What was your actual outcome?
      value: I had the following actual outcome...
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: On Which OS have you tried it?
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
  - type: dropdown
    id: Server
    attributes:
      label: What was your server version?
      multiple: true
      options:
        - Azure DevOps Services
        - Azure DevOps Server 2020
        - Azure DevOps Server 2019
        - other (specify)
  - type: input
    id: other-server
    attributes:
      label: 'Other server version'
      description: If you chose 'other' for server specify the version here. Please be aware that we do not support all versions and the bug might get closed.
      placeholder: 'Specify the version'
  - type: textarea
    id: vsteam-api-output
    attributes:
      label: Log output of used API
      description: Please copy and paste the output generated by `Get-VSTeamAPIVersion`.
      render: shell
    validations:
      required: true
  - type: textarea
    id: vsteam-psversiontable
    attributes:
      label: Log output of $PSVersionTable
      description: Please copy and paste the output generated by `$PSVersionTable`.
      render: shell
    validations:
      required: true
