blank_issues_enabled: false
contact_links:
  - name: VSTeam docs
    url: https://methodsandpractices.github.io/vsteam-docs/docs/modules/vsteam
    about: RTFM
  - name: VSTeam Q&A
    url: https://github.com/MethodsAndPractices/vsteam/discussions
    about: This is for general questions / discussions without bugs or requests.
