name: 'test publish'

on:
  workflow_dispatch:

jobs:
  publish-stage:
    name: Publish Test
    runs-on: ubuntu-latest
    env:
      module_version: "10.0.0"
    permissions: write-all
    steps:

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        commit: trunk
        tag: "v${{ env.module_version }}"
        discussionCategory: "Announcements"
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
